version: '3.8'
services:
  api_service:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - db

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg: