name: Test coverage

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      #       checkout
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Maven Verify
        env:
          JDBC_DATABASE_URL: ${{secrets.JDBC_DATABASE_URL}}
          JDBC_DATABASE_USERNAME: ${{secrets.JDBC_DATABASE_USERNAME}}
          JDBC_DATABASE_PASSWORD: ${{secrets.JDBC_DATABASE_PASSWORD}}
          TELEGRAMBOT_TOKEN: ${{secrets.TELEGRAMBOT_TOKEN}}
        run:  mvn -B clean verify
      - name: Test Coverage
        uses: codecov/codecov-action@v3


